<a href="https://colab.research.google.com/github/annatsamoyra-prog/data-story-/blob/main/protothema_technology_2026_scraper_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q requests beautifulsoup4 pandas numpy matplotlib spacy
!python -m spacy download el_core_news_sm

Collecting el-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/el_core_news_sm-3.8.0/el_core_news_sm-3.8.0-py3-none-any.whl (12.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 25.7 MB/s eta 0:00:00
Installing collected packages: el-core-news-sm
Successfully installed el-core-news-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('el_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
# scraping
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import json
import xml.etree.ElementTree as ET   # για να διαβάσουμε το RSS feed (είναι απλό XML)

# για τα nan values
import numpy as np

# για τα γραφήματα
import matplotlib.pyplot as plt

# για την επεξεργασία ελληνικών κειμένων (χρήσιμο αργότερα για ανάλυση, όχι για το scraping)
import spacy

In [ ]:
main_url = "https://www.protothema.gr"
category_url = "https://www.protothema.gr/technology/"
rss_url = "https://www.protothema.gr/technology/rss/"

target_year = 2026

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    )
}

# Boilerplate phrases -- μόλις εμφανιστεί μία από αυτές μέσα σε παράγραφο, σταματάμε να
# μαζεύουμε κείμενο (ίδια λογική με το STOP_PHRASES του tovima παραδείγματος).
STOP_PHRASES = [
    "Σχετικά Άρθρα",
    "ΡΟΗ ΕΙΔΗΣΕΩΝ",
    "ΤΑ ΠΙΟ ΔΗΜΟΦΙΛΗ",
    "Δείτε Επίσης",
    "Best of Network",
    "Thema Insights",
]

## ΒΗΜΑ Α: Μαζεύουμε τα urls των άρθρων (teasers) μέσω RSS

Ρόλος ίδιος με τη λούπα σελίδων του efsyn tutorial: θέλουμε μια λίστα από urls άρθρων. Το RSS
feed μας τη δίνει με ένα request αντί για πολλές σελίδες.

In [ ]:
response = requests.get(rss_url, headers=HEADERS)
root = ET.fromstring(response.content)

teasers_list = []
for item in root.findall(".//item"):
    link_tag = item.find("link")
    if link_tag is None or not link_tag.text:
        continue
    story_dict = {"url": link_tag.text.strip()}
    teasers_list.append(story_dict)

protothema_teasers_df = pd.DataFrame(teasers_list)
protothema_teasers_df = protothema_teasers_df.drop_duplicates(subset=["url"]).reset_index(drop=True)
protothema_teasers_df

                                                  url
0   https://www.protothema.gr/technology/article/1...
1   https://www.protothema.gr/technology/article/1...
2   https://www.protothema.gr/technology/article/1...
3   https://www.protothema.gr/technology/article/1...
4   https://www.protothema.gr/technology/article/1...
..                                                ...
95  https://www.protothema.gr/technology/article/1...
96  https://www.protothema.gr/technology/article/1...
97  https://www.protothema.gr/technology/article/1...
98  https://www.protothema.gr/technology/article/1...
99  https://www.protothema.gr/technology/article/1...

[100 rows x 1 columns]

In [ ]:
# Αποθηκεύουμε τα teaser urls σε csv, ίδια λογική με το efsyn tutorial (μπορείς να αλλάξεις
# το path αν θες να το σώσεις στο Google Drive σου).
protothema_teasers_df.to_csv("protothema_teasers_technology_2026.csv", index=False)

## ΒΗΜΑ Β: Δοκιμή σε ένα άρθρο πριν φτιάξουμε τη λούπα

Ίδια λογική με το ΒΗΜΑ 5 του tutorial: πρώτα δοκιμάζουμε σε ένα άρθρο, βλέπουμε ότι δουλεύει, και
μετά φτιάχνουμε τη λούπα για όλα.

In [ ]:
article_url = protothema_teasers_df.loc[0, "url"]
print(article_url)

response = requests.get(article_url, headers=HEADERS)
doc = BeautifulSoup(response.text, "html.parser")

# Το html tag <article> συνήθως χρησιμοποιείται μόνο για το κυρίως άρθρο, οπότε -όπως λέει και
# το tutorial- δεν χρειάζεται να καταγράψουμε class. Αν σε κάποιο άρθρο δεν υπάρχει <article>,
# πέφτουμε πίσω σε ολόκληρο το doc.
article = doc.find("article") or doc
print(article.prettify()[:3000])

https://www.protothema.gr/technology/article/1880080/h-openai-apokalupse-nea-peristatika-me-tin-tehniti-noimosuni-oi-aprosdokites-i-anisuhitikes-suberifores-ton-modelon/?utm_source=rss
<article>
 <a class="mainLink" href="https://www.protothema.gr/world/article/1879227/proin-ereunitis-tis-google-bike-ston-horo-kai-proeidopoiise-gia-tin-apeili-tis-tehnitis-noimosunis/">
 </a>
 <figure data-image-mode="article">
  <a href="https://www.protothema.gr/world/article/1879227/proin-ereunitis-tis-google-bike-ston-horo-kai-proeidopoiise-gia-tin-apeili-tis-tehnitis-noimosunis/">
   <picture>
    <!--[if IE 9]><video style="display: none;"><![endif]-->
    <source class="lazysrcset" data-srcset="https://i1.prth.gr/images/304x304/2/jpg/files/2026-06-13/artificial_inteligence_xr.webp" media="(max-width: 639px)" type="image/webp"/>
    <source class="lazysrcset" data-srcset="https://i1.prth.gr/images/304x304/2/jpg/files/2026-06-13/artificial_inteligence_xr.jp2" media="(max-width: 639px)" type="image/jp2"/>
    <source class="lazysrcset" data-srcset="https://i1.prth.gr/images/360x203/2/jpg/files/2026-06-13/artificial_inteligence_xr.webp" media="(min-width: 640px)" type="image/webp"/>
    <source class="lazysrcset" data-srcset="https://i1.prth.gr/images/360x203/2/jpg/files/2026-06-13/artificial_inteligence_xr.jp2" media="(min-width: 640px)" type="image/jp2"/>
    <!--[if IE 9]></video><![endif]-->
    <img alt="Πρώην ερευνητής της Google προειδοποιεί  για την απειλή της Τεχνητής Νοημοσύνης, «η AI μπορεί να σκοτώσει όλους τους ανθρώπους»" class="lazy" data-src="https://i1.prth.gr/images/360x203/2/jpg/files/2026-06-13/artificial_inteligence_xr.jpg"/>
   </picture>
  </a>
 </figure>
 <div class="desc">
  <div class="heading">
   <h3>
    <a href="https://www.protothema.gr/world/article/1879227/proin-ereunitis-tis-google-bike-ston-horo-kai-proeidopoiise-gia-tin-apeili-tis-tehnitis-noimosunis/">
     H AI μπορεί να σκοτώσει όλους τους ανθρώπους, λέει ερευνητής που έφυγε από την Google και χτυπάει καμπανάκι, «o χρόνος μας τελειώνει»
    </a>
   </h3>
  </div>
  <div class="wrp">
   <span class="update_well">
    <time data-timeago="" datetime="2026-09-15T18:33:00+03:00">
     15.09.2026, 18:33
    </time>
   </span>
  </div>
 </div>
</article>

In [ ]:
# Τίτλος -- ο τίτλος συνήθως είναι σε h1 tag
title = article.find("h1").text.strip() if article.find("h1") else None
title

In [ ]:
# Ημερομηνία -- το protothema δεν έχει <time datetime=...> σαν το efsyn, έχει αυτό το meta
# tag στο <head> της σελίδας, με την ίδια λειτουργία (έτοιμη μορφή για pd.to_datetime).
meta_date = doc.find("meta", {"property": "article:published_time"})
date = meta_date["content"] if meta_date else None
date

'2026-09-17T09:50:00+03:00'

In [ ]:
# Συντάκτης δεν βρέθηκε ορατό byline tag/class στα δείγματα που ελέγχθηκαν, οπότε ψάχνουμε
# στα δομημένα δεδομένα JSON-LD του άρθρου (πολύ συχνό σε σύγχρονα news sites). Αν δεν υπάρχει,
# ο author μένει None -- δεν μαντεύουμε.
author = None
for script in doc.find_all("script", type="application/ld+json"):
    try:
        data = json.loads(script.string)
    except (TypeError, ValueError):
        continue
    if isinstance(data, dict) and "author" in data:
        a = data["author"]
        if isinstance(a, dict):
            author = a.get("name")
        elif isinstance(a, list) and a:
            author = a[0].get("name")
        break
author

In [ ]:
# μαζεύουμε όλα τα <p> tags
# μέχρι να συναντήσουμε μια από τις STOP_PHRASES.
p_texts_list = []
for p in article.find_all("p"):
    text = p.text.strip()
    if not text:
        continue
    if any(stop in text for stop in STOP_PHRASES):
        break
    p_texts_list.append(text)

full_text = " ".join(p_texts_list)
full_text = "".join(full_text.splitlines())
full_text

''

## ΒΗΜΑ Γ: Η λούπα για όλα τα άρθρα

Ίδια δομή με το tutorial: για κάθε url φτιάχνουμε ένα `story_dict`, το προσθέτουμε σε μια λίστα,
και στο τέλος τη μετατρέπουμε σε DataFrame.

In [ ]:
articles_list = []

for i, row in protothema_teasers_df.iterrows():
    url = row["url"]
    print(f"{i+1}/{len(protothema_teasers_df)}: {url}")

    try:
        response = requests.get(url, headers=HEADERS, timeout=15)
        doc = BeautifulSoup(response.text, "html.parser")
        article = doc.find("article") or doc

        title = article.find("h1").text.strip() if article.find("h1") else None

        meta_date = doc.find("meta", {"property": "article:published_time"})
        date = meta_date["content"] if meta_date else None

        author = None
        for script in doc.find_all("script", type="application/ld+json"):
            try:
                data = json.loads(script.string)
            except (TypeError, ValueError):
                continue
            if isinstance(data, dict) and "author" in data:
                a = data["author"]
                if isinstance(a, dict):
                    author = a.get("name")
                elif isinstance(a, list) and a:
                    author = a[0].get("name")
                break

        p_texts_list = []
        for p in article.find_all("p"):
            text = p.text.strip()
            if not text:
                continue
            if any(stop in text for stop in STOP_PHRASES):
                break
            p_texts_list.append(text)
        full_text = " ".join(p_texts_list)
        full_text = "".join(full_text.splitlines())

        story_dict = {
            "site": "protothema.gr",
            "url": url,
            "title": title,
            "date": date,
            "author": author,
            "full_text": full_text if full_text else None,
        }
    except Exception as e:
        print("  -> Σφάλμα:", e)
        story_dict = {
            "site": "protothema.gr", "url": url, "title": None,
            "date": None, "author": None, "full_text": None,
        }

    articles_list.append(story_dict)
    time.sleep(1)

1/100: https://www.protothema.gr/technology/article/1880080/h-openai-apokalupse-nea-peristatika-me-tin-tehniti-noimosuni-oi-aprosdokites-i-anisuhitikes-suberifores-ton-modelon/?utm_source=rss
2/100: https://www.protothema.gr/technology/article/1879087/tehniti-noimosuni-horis-frena-oi-dimiourgoi-tis-ai-arhisan-na-fovoudai/?utm_source=rss
3/100: https://www.protothema.gr/technology/article/1878018/i-ai-diavazei-tin-kardia-prin-nosisei-ti-apokaluptoun-mastografia-kai-fotografies-prosopou/?utm_source=rss
4/100: https://www.protothema.gr/technology/article/1876627/samsung-kata-apple-mas-adigrapsate-to-trolarisma-gia-to-neo-iphone/?utm_source=rss
5/100: https://www.protothema.gr/technology/article/1876521/to-iphone-duo-pou-diplonei-kai-kostizei-2399-euro-epanastatis-i-ouragos/?utm_source=rss
6/100: https://www.protothema.gr/technology/article/1876359/apo-1999-to-neo-anadiploumeno-iphone-duo-pou-kukloforei-stis-16-oktovriou-sta-1199-to-iphone-18/?utm_source=rss
7/100: https://www.protothema.gr/technology/article/1876059/i-cloudevo-sto-epikedro-diethnous-case-study-tis-google-gia-tin-tehniti-noimosuni/?utm_source=rss
8/100: https://www.protothema.gr/technology/article/1875417/adistrofi-metrisi-gia-tin-parousiasi-tou-anadiploumenou-iphone-to-proto-megalo-stoihima-tou-neou-ceo-tis-apple/?utm_source=rss
9/100: https://www.protothema.gr/technology/article/1873792/h-lego-kanei-voutia-sti-nostalgia-me-to-eduposiako-proto-playstation-deite-video/?utm_source=rss
10/100: https://www.protothema.gr/technology/article/1873733/robot-sti-rosia-tsadistike-epeidi-to-esproxe-pelatis-kai-tou-epitethike-deite-video/?utm_source=rss
11/100: https://www.protothema.gr/technology/article/1864065/to-spotify-tha-arhisei-na-markarei-ta-tragoudia-pou-einai-ftiagmena-apo-tehniti-noimosuni/?utm_source=rss
12/100: https://www.protothema.gr/technology/article/1858622/meta-tin-openai-kai-i-anthropic-tria-modela-tehnitis-noimosunis-claude-vgikan-apo-kleisto-perivallon-dokimon-kai-hakaran/?utm_source=rss
13/100: https://www.protothema.gr/technology/article/1855979/blak-aout-sto-chatgpt-anafores-gia-polla-provlimata-stin-platforma-tis-openai/?utm_source=rss
14/100: https://www.protothema.gr/technology/article/1855882/exupnes-poleis-ti-hreiazetai-enas-dimos-gia-na-perasei-sti-nea-psifiaki-epohi/?utm_source=rss
15/100: https://www.protothema.gr/technology/article/1853148/epese-to-facebook-dekades-anafores-gia-provlimata/?utm_source=rss
16/100: https://www.protothema.gr/technology/article/1850070/i-tehnologia-ton-deepfakes-apo-ton-doko-sto-moudial/?utm_source=rss
17/100: https://www.protothema.gr/technology/article/1848762/i-ee-katigorei-ti-meta-gia-ethistiko-shediasmo-se-instagram-kai-facebook-kai-kinduneuei-me-prostimo/?utm_source=rss
18/100: https://www.protothema.gr/technology/article/1845457/erhetai-to-proto-xenodoheio-ston-kosmo-pou-tha-leitourgei-apokleistika-me-robotiko-prosopiko-anoigei-to-2027-stin-kina/?utm_source=rss
19/100: https://www.protothema.gr/technology/article/1845268/anthropoeidi-robot-paizoun-podosfairo-kai-dokimazoun-ta-oria-tis-tehnitis-noimosunis/?utm_source=rss
20/100: https://www.protothema.gr/technology/article/1845013/viral-sta-social-media-i-proseggisi-gia-tin-uperpliroforisi-ston-sughrono-kosmo-deite-video/?utm_source=rss
21/100: https://www.protothema.gr/technology/article/1844033/i-sony-kovei-ta-diskakia-gia-to-playstation-apo-to-2028-mono-psifiaka-tha-kukloforoun-ta-paihnidia/?utm_source=rss
22/100: https://www.protothema.gr/technology/article/1840936/ta-public-ependuoun-stin-agora-ton-ai-suskeuon-kai-fernoun-tin-tehniti-noimosuni-stin-kathimerinotita/?utm_source=rss
23/100: https://www.protothema.gr/technology/article/1837043/i-apple-proanaggellei-auxiseis-timon-sta-proioda-tis-logo-elleipseon-sta-tsip-mnimis/?utm_source=rss
24/100: https://www.protothema.gr/technology/article/1829589/hasabis-os-to-2030-i-tehniti-noimosuni-tha-borei-na-ektelei-gnostika-kathikoda-opos-o-anthropos/?utm_source=rss
25/100: https://www.protothema.gr/technology/article/1829481/cosmote-telekom-dunamiki-parousia-sto-diethnes-festival-tehnologias-kai-epiheirimatikotitas-panathnea-2026/?utm_source=rss
26/100: https://www.protothema.gr/technology/article/1828795/to-god-of-war-epistrefei-alla-horis-ton-spartiati-kratos-gunaika-i-protagonistria-tou-neou-video-game-deite-video/?utm_source=rss
27/100: https://www.protothema.gr/technology/article/1823837/programma-tehnitis-noimosunis-edopizei-iliakes-kataigides-kai-fusikes-katastrofes/?utm_source=rss
28/100: https://www.protothema.gr/technology/article/1821743/public-nea-ebeiria-theasis-me-xl-tileoraseis/?utm_source=rss
29/100: https://www.protothema.gr/technology/article/1821437/i-google-allazei-tin-bara-anazitisis-gia-proti-fora-meta-apo-25-hronia/?utm_source=rss
30/100: https://www.protothema.gr/technology/article/1821073/vasikos-ependutis-sto-xekinima-tis-anthropic-itan-o-demis-hasabis-lene-oi-financial-times/?utm_source=rss
31/100: https://www.protothema.gr/technology/article/1820874/giati-oi-katanalotes-kratoun-ta-kinita-tous-sta-surtaria-pano-apo-53-dis-oi-ahrisimopoiites-suskeues/?utm_source=rss
32/100: https://www.protothema.gr/technology/article/1819564/to-ai-stin-upiresia-tis-kardiologias-pos-oi-algorithmoi-boroun-na-prolavoun-egefalika-epeisodia/?utm_source=rss
33/100: https://www.protothema.gr/technology/article/1819384/gigadiaio-robot-apo-tin-kina-spaei-ta-oria-tis-epistimonikis-fadasias/?utm_source=rss
34/100: https://www.protothema.gr/technology/article/1819146/ti-einai-ta-instants-i-nea-leitourgia-tou-instagram-gia-authormites-fotografies-pou-exafanizodai/?utm_source=rss
35/100: https://www.protothema.gr/technology/article/1816862/panellinios-diagonismos-stem-2026-ekei-opou-i-tehniti-noimosuni-sunada-ti-dimiourgikotita-ton-paidion/?utm_source=rss
36/100: https://www.protothema.gr/technology/article/1816184/giorti-tis-miteras-to-doodle-tis-google-einai-afieromeno-se-oles-tis-mamades-tou-kosmou/?utm_source=rss
37/100: https://www.protothema.gr/technology/article/1813699/bataria-kamera-ai-pos-allazoun-ta-smartphones-to-2026/?utm_source=rss
38/100: https://www.protothema.gr/technology/article/1811400/i-sunarpastiki-poreia-metavasis-pros-to-6g-ehei-idi-xekinisei/?utm_source=rss
39/100: https://www.protothema.gr/technology/article/1811382/nea-leitourgia-sto-apple-watch-kai-to-iphone-gia-na-min-xanahaseis-to-xupnitiri/?utm_source=rss
40/100: https://www.protothema.gr/technology/article/1808195/google-cloud-next-2026-nea-epohi-gia-ai-agents-dedomena-kai-kuvernoasfaleia/?utm_source=rss
41/100: https://www.protothema.gr/technology/article/1806765/google-doodle-afieromeno-stin-imera-tis-gis-me-eikones-apo-to-google-earth/?utm_source=rss
42/100: https://www.protothema.gr/technology/article/1806076/poios-einai-o-tzon-ternous-o-neos-ceo-tis-apple-o-mihanikos-pou-analamvanei-tin-etaireia-ton-4-tris-dolarion/?utm_source=rss
43/100: https://www.protothema.gr/technology/article/1806033/telos-epohis-stin-apple-15-hronia-ap-otan-diadehthike-ton-stiv-tzobs-o-tim-kouk-apohorei-apo-tin-igesia/?utm_source=rss
44/100: https://www.protothema.gr/technology/article/1805607/xifaskia-san-video-game-stin-iaponia-aneptuxan-sustima-ai-pou-apokaluptei-tin-poreia-tou-xifous-se-pragmatiko-hrono/?utm_source=rss
45/100: https://www.protothema.gr/technology/article/1804634/ponokefalos-gia-tous-amerikanous/?utm_source=rss
46/100: https://www.protothema.gr/technology/article/1803708/deite-video-robot-basketbolistas-pou-vasizetai-apokleistika-stin-tehniti-noimosuni-eduposiase-sto-parke/?utm_source=rss
47/100: https://www.protothema.gr/technology/article/1801854/tehniti-noimosuni-kai-psuhiki-ugeia-mia-nea-pragmatikotita-anamesa-se-algorithmous-kai-anthropines-anages/?utm_source=rss
48/100: https://www.protothema.gr/technology/article/1794151/oi-5-vasikes-allages-sta-iphone-pou-fernei-to-ios-264-nea-ergaleia-kai-voitheia-apo-to-ai/?utm_source=rss
49/100: https://www.protothema.gr/technology/article/1793779/google-doodle-gia-tin-25i-martiou-pos-tima-tin-elliniki-epeteio/?utm_source=rss
50/100: https://www.protothema.gr/technology/article/1793098/epese-to-h-anafores-gia-provlimata-apo-tous-hristes/?utm_source=rss
51/100: https://www.protothema.gr/technology/article/1792984/pos-ta-ai-chatbots-allazoun-to-marketing-kai-tis-diafimiseis/?utm_source=rss
52/100: https://www.protothema.gr/technology/article/1792971/pos-tha-emfanizesai-pio-suhna-sta-ai-chatbots/?utm_source=rss
53/100: https://www.protothema.gr/technology/article/1792951/pos-tha-se-vriskoun-eukola-oi-pelates-meso-ai-search/?utm_source=rss
54/100: https://www.protothema.gr/technology/article/1790401/ti-deihnoun-oi-sunomilies-metaxu-ai-agent-kai-hristi/?utm_source=rss
55/100: https://www.protothema.gr/technology/article/1790398/pos-oi-ai-agents-adloun-plirofories-apo-crm-vaseis-dedomenon-kai-sustimata-upostirixis/?utm_source=rss
56/100: https://www.protothema.gr/technology/article/1790388/pos-oi-ai-agents-metatrepoun-ti-forma-epikoinonias-se-sunomilia-fusikis-glossas/?utm_source=rss
57/100: https://www.protothema.gr/technology/article/1790386/pos-ena-chatbot-borei-na-voithisei-ti-leitourgia-mias-epiheirisis/?utm_source=rss
58/100: https://www.protothema.gr/technology/article/1790379/o-rolos-ton-ai-agents-pos-ena-website-katalavainei-ti-thelei-o-episkeptis/?utm_source=rss
59/100: https://www.protothema.gr/technology/article/1790368/pos-oi-ai-agents-allazoun-ton-tropo-pou-leitourgoun-ta-websites/?utm_source=rss
60/100: https://www.protothema.gr/technology/article/1789783/giati-ta-kinita-den-poloudai-pia-me-fortisti/?utm_source=rss
61/100: https://www.protothema.gr/technology/article/1786930/ta-163-nea-emojis-erhodai-sta-iphone-apo-paramorfomeno-prosopo-kai-bigfoot-mehri-orka-kai-katolisthisi/?utm_source=rss
62/100: https://www.protothema.gr/technology/article/1786381/giati-oi-ai-agents-den-apoteloun-mono-ena-chatbot/?utm_source=rss
63/100: https://www.protothema.gr/technology/article/1786379/pos-oi-ai-agents-apoktoun-leitourgiko-rolo/?utm_source=rss
64/100: https://www.protothema.gr/technology/article/1786373/ai-agents-os-ergaleio-eborikis-anaptuxis/?utm_source=rss
65/100: https://www.protothema.gr/technology/article/1784469/sunagermos-gia-tous-hristes-suskeuon-android-edopistike-neo-kakovoulo-logismiko/?utm_source=rss
66/100: https://www.protothema.gr/technology/article/1783880/poia-einai-ta-haraktiristika-tou-neou-iphone-17e-oi-pio-megales-allages/?utm_source=rss
67/100: https://www.protothema.gr/technology/article/1783472/apo-ta-keywords-sta-prompts-i-stratigiki-metavasi-stin-ai-anazitisi/?utm_source=rss
68/100: https://www.protothema.gr/technology/article/1783459/ai-visibility-kai-answer-engine-optimization-i-nea-pragmatikotita-stin-anazitisi/?utm_source=rss
69/100: https://www.protothema.gr/technology/article/1783418/ai-visibility-kai-information-architecture-giati-i-domi-proigeitai-tou-periehomenou/?utm_source=rss
70/100: https://www.protothema.gr/technology/article/1780419/instagram-tha-eidopoiei-goneis-ean-efivoi-anazitoun-periehomeno-me-autoktonia-se-ipa-vretania-australia-kai-kanada/?utm_source=rss
71/100: https://www.protothema.gr/technology/article/1779769/to-epomeno-vima-stin-tehniti-noimosuni-borei-ena-modelo-ai-na-ehei-suneidisi-na-aisthanetai-na-zei-akoma/?utm_source=rss
72/100: https://www.protothema.gr/technology/article/1776100/allages-sto-messenger-ti-simainei-i-katargisi-ton-desktop-ekdoseon-gia-tous-hristes/?utm_source=rss
73/100: https://www.protothema.gr/technology/article/1775206/tehniti-noimosuni-sti-mousiki-giati-134-ekat-ai-kommatia-katevikan-apo-platformes-oi-prokliseis-kai-ta-oria/?utm_source=rss
74/100: https://www.protothema.gr/technology/article/1774928/provlimata-sto-h-stin-athina-anafores-gia-duskolies-stin-prosvasi-ston-istotopo-kai-tin-efarmogi/?utm_source=rss
75/100: https://www.protothema.gr/technology/article/1774229/enas-ellinas-gia-proti-fora-se-programma-ekpaideusis-astronauton-tou-europaikou-organismou-diastimatos/?utm_source=rss
76/100: https://www.protothema.gr/technology/article/1773482/to-neo-ios-prosthetei-tin-epilogi-transfer-to-android-kai-dieukolunei-ti-metavasi-apo-apple-se-google/?utm_source=rss
77/100: https://www.protothema.gr/technology/article/1769621/mathitis-lukeiou-stis-ipa-edopise-15-ekat-agnosta-diastimika-adikeimena-me-tehniti-noimosuni/?utm_source=rss
78/100: https://www.protothema.gr/technology/article/1768548/tilefoniki-epikoinonia-eihan-donald-trab-kai-si-tzinping/?utm_source=rss
79/100: https://www.protothema.gr/technology/article/1766090/i-proseggisi-tis-cloudevo-stin-anaptuxi-eleghomenon-sustimaton-conversational-ai/?utm_source=rss
80/100: https://www.protothema.gr/technology/article/1766087/to-neo-ai-dialogue-system-tou-elvetikou-brand-viiala-me-tin-upografi-tis-cloudevo/?utm_source=rss
81/100: https://www.protothema.gr/technology/article/1765863/i-ai-powered-aggliki-ekdosi-tou-protou-thematos-me-tin-upografi-tis-cloudevo/?utm_source=rss
82/100: https://www.protothema.gr/technology/article/1765408/ai-takeaways-neo-ai-ergaleio-tis-cloudevo-gia-ti-sunoptiki-parousiasi-eidiseon/?utm_source=rss
83/100: https://www.protothema.gr/technology/article/1764821/semantic-search-nea-efarmogi-tehnitis-noimosunis-tis-cloudevo/?utm_source=rss
84/100: https://www.protothema.gr/technology/article/1764581/spania-astronomika-adikeimena-edopise-mia-omada-astronomon-me-ergaleio-ai/?utm_source=rss
85/100: https://www.protothema.gr/technology/article/1764008/upo-austiri-epopteia-apo-tin-ee-tithetai-to-whatsapp-poioi-kindunoi-edopizodai-gia-tous-hristes/?utm_source=rss
86/100: https://www.protothema.gr/technology/article/1763545/i-komision-xekinise-ereuna-gia-to-grok-tou-mask-gia-asemnes-eikones/?utm_source=rss
87/100: https://www.protothema.gr/technology/article/1761753/ouasington-kai-pekino-ekleisan-to-deal-gia-to-tiktok-oracle-kai-silver-lake-igoudai-koinopraxias-amerikanon-ependuton/?utm_source=rss
88/100: https://www.protothema.gr/technology/article/1761146/epese-to-yahoo-mail-horis-prosvasi-sto-ilektroniko-tous-tahudromeio-hiliades-hristes/?utm_source=rss
89/100: https://www.protothema.gr/technology/article/1760312/ta-oria-ston-hrono-othonis-ton-paidion-den-arkoun-pleon-gia-na-ta-prostatepsoun-proeidopoioun-eidikoi/?utm_source=rss
90/100: https://www.protothema.gr/technology/article/1759255/ellinikoi-doruforoi-kategrapsan-apo-to-diastima-ti-fregata-kimon-na-ftanei-stin-ellada-deite-fotografia/?utm_source=rss
91/100: https://www.protothema.gr/technology/article/1758682/epese-to-x/?utm_source=rss
92/100: https://www.protothema.gr/technology/article/1756504/pio-steni-i-shesi-apple-kai-google-me-to-modelo-tehnitis-noimosunis-gemini-tha-leitourgei-i-siri/?utm_source=rss
93/100: https://www.protothema.gr/technology/article/1756178/sovaros-kindunos-gia-tin-asfaleia-ton-iphone-ekatommuria-suskeues-ektetheimenes-epeidi-oi-hristes-den-anavathmizoun-se/?utm_source=rss
94/100: https://www.protothema.gr/technology/article/1755159/grok-apenergopoiise-dimiourgia-eikonas-gia-mi-sundromites-kataggelies-gia-asemnes-fotografies-gunaikon-kai-paidion/?utm_source=rss
95/100: https://www.protothema.gr/technology/article/1755129/poia-agnosti-leitourgia-ton-iphone-boroume-na-apenergopoiisoume-gia-na-stamatisoume-tous-haker/?utm_source=rss
96/100: https://www.protothema.gr/technology/article/1753604/i-lego-anakoinose-to-smart-brick-ti-simadikoteri-exelixi-tis-ta-teleutaia-50-hronia/?utm_source=rss
97/100: https://www.protothema.gr/technology/article/1752308/apo-tin-tesla-kai-tin-amazon-eos-ti-disney-ta-anthropoeidi-robot-bainoun-sti-zoi-mas/?utm_source=rss
98/100: https://www.protothema.gr/technology/article/1750462/sunagermos-apo-tin-apple-zita-amesi-enimerosi-logismikou-sto-iphone-kai-ipad-gia-krisimi-apeili-asfaleias/?utm_source=rss
99/100: https://www.protothema.gr/technology/article/1748931/nea-epohi-sta-e-mail-etoimazei-i-google-osoi-theloun-tha-boroun-na-allaxoun-dieuthunsi-gmail/?utm_source=rss
100/100: https://www.protothema.gr/technology/article/1747894/spanious-meteorites-anakalupse-i-kineziki-apostoli-stin-atheati-pleura-tis-selinis/?utm_source=rss

## ΒΗΜΑ Δ: DataFrame, φιλτράρισμα στο 2026, καθάρισμα

In [ ]:
protothema_df = pd.DataFrame(articles_list)

# Μετατροπή date (string) σε πραγματικό datetime -- ίδια λογική με το efsyn NLP notebook
# (pd.to_datetime), απλά εδώ το date string έχει ήδη ζώνη ώρας μέσα του (π.χ. "+03:00").
protothema_df["datetime"] = pd.to_datetime(protothema_df["date"], errors="coerce", utc=True)
protothema_df["datetime"] = protothema_df["datetime"].dt.tz_convert("Europe/Athens").dt.tz_localize(None)

protothema_df = protothema_df[["site", "url", "title", "date", "author", "full_text", "datetime"]]
protothema_df.head()

,site,url,title,date,author,full_text,datetime
0,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-17T09:50:00+03:00,None,None,2026-09-17 09:50:00
1,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-15T16:49:00+03:00,Δημήτρης Παγαδάκης,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-09-15 16:49:00
2,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-13T10:48:00+03:00,None,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-09-13 10:48:00
3,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-10T10:46:00+03:00,None,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-09-10 10:46:00
4,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-10T07:09:00+03:00,Βασίλης Τσακίρογλου,None,2026-09-10 07:09:00

In [ ]:
protothema_2026_df = protothema_df[
    (protothema_df["datetime"] >= f"{target_year}-01-01")
    & (protothema_df["datetime"] < f"{target_year + 1}-01-01")
].copy()

protothema_2026_df = protothema_2026_df.drop_duplicates(subset=["url"]).reset_index(drop=True)
protothema_2026_df = protothema_2026_df.sort_values("datetime").reset_index(drop=True)

print("Πλήθος άρθρων:", len(protothema_2026_df))
protothema_2026_df.head()

Πλήθος άρθρων: 92

,site,url,title,date,author,full_text,datetime
0,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-03T22:40:00+02:00,Κώστας Μαρτάκης,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-03 22:40:00
1,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-05T17:58:00+02:00,None,None,2026-01-05 17:58:00
2,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-06T16:51:00+02:00,None,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-06 16:51:00
3,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-09T15:14:08+02:00,None,None,2026-01-09 15:14:08
4,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-10T08:30:02+02:00,None,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-10 08:30:02

In [ ]:
start_page = 1
end_page = 5
start_url = "https://www.protothema.gr/technology/???page="   # <- βάλε το σωστό pattern εδώ

extra_teasers = []
for page_num in range(start_page, end_page + 1):
    page_url = start_url + str(page_num)
    response = requests.get(page_url, headers=HEADERS)
    doc = BeautifulSoup(response.text, "html.parser")
    for a in doc.find_all("a", href=True):
        href = a["href"]
        if "/technology/article/" in href:
            full_url = href if href.startswith("http") else main_url + href
            extra_teasers.append({"url": full_url})
    time.sleep(1)

extra_teasers_df = pd.DataFrame(extra_teasers).drop_duplicates(subset=["url"])
print(len(extra_teasers_df))

19

## Αποθήκευση

In [ ]:
protothema_2026_df.to_csv("protothema_technology_2026.csv", index=False, encoding="utf-8-sig")
print("Αποθηκεύτηκε: protothema_technology_2026.csv (%d γραμμές)" % len(protothema_2026_df))

Αποθηκεύτηκε: protothema_technology_2026.csv (92 γραμμές)

## Γρήγορος έλεγχος

In [ ]:
print("Σύνολο άρθρων:", len(protothema_2026_df))
print("\nΆρθρα ανά μήνα:")
print(protothema_2026_df["datetime"].dt.to_period("M").value_counts().sort_index())
print("\nMin datetime:", protothema_2026_df["datetime"].min())
print("Max datetime:", protothema_2026_df["datetime"].max())
print("\nMissing values ανά στήλη:")
print(protothema_2026_df.isna().sum())

n = min(10, len(protothema_2026_df))
print(f"\n{n} τυχαία urls:")
for u in protothema_2026_df["url"].sample(n=n).tolist():
    print(" -", u)

n2 = min(5, len(protothema_2026_df))
print(f"\n{n2} τυχαία δείγματα:")
for _, row in protothema_2026_df.sample(n=n2).iterrows():
    print("\n---")
    print("Title:", row["title"])
    print("Author:", row["author"])
    print("Datetime:", row["datetime"])
    print("Text[:500]:", (row["full_text"] or "")[:500])

Σύνολο άρθρων: 92

Άρθρα ανά μήνα:
datetime
2026-01    24
2026-02    14
2026-03     7
2026-04     9
2026-05    12
2026-06     5
2026-07    10
2026-08     2
2026-09     9
Freq: M, Name: count, dtype: int64

Min datetime: 2026-01-03 22:40:00
Max datetime: 2026-09-17 09:50:00

Missing values ανά στήλη:
site          0
url           0
title        92
date          0
author       84
full_text    29
datetime      0
dtype: int64

10 τυχαία urls:
 - https://www.protothema.gr/technology/article/1786381/giati-oi-ai-agents-den-apoteloun-mono-ena-chatbot/?utm_source=rss
 - https://www.protothema.gr/technology/article/1790401/ti-deihnoun-oi-sunomilies-metaxu-ai-agent-kai-hristi/?utm_source=rss
 - https://www.protothema.gr/technology/article/1786379/pos-oi-ai-agents-apoktoun-leitourgiko-rolo/?utm_source=rss
 - https://www.protothema.gr/technology/article/1848762/i-ee-katigorei-ti-meta-gia-ethistiko-shediasmo-se-instagram-kai-facebook-kai-kinduneuei-me-prostimo/?utm_source=rss
 - https://www.protothema.gr/technology/article/1768548/tilefoniki-epikoinonia-eihan-donald-trab-kai-si-tzinping/?utm_source=rss
 - https://www.protothema.gr/technology/article/1876059/i-cloudevo-sto-epikedro-diethnous-case-study-tis-google-gia-tin-tehniti-noimosuni/?utm_source=rss
 - https://www.protothema.gr/technology/article/1823837/programma-tehnitis-noimosunis-edopizei-iliakes-kataigides-kai-fusikes-katastrofes/?utm_source=rss
 - https://www.protothema.gr/technology/article/1821743/public-nea-ebeiria-theasis-me-xl-tileoraseis/?utm_source=rss
 - https://www.protothema.gr/technology/article/1776100/allages-sto-messenger-ti-simainei-i-katargisi-ton-desktop-ekdoseon-gia-tous-hristes/?utm_source=rss
 - https://www.protothema.gr/technology/article/1806765/google-doodle-afieromeno-stin-imera-tis-gis-me-eikones-apo-to-google-earth/?utm_source=rss

5 τυχαία δείγματα:

---
Title: None
Author: None
Datetime: 2026-02-16 15:41:00
Text[:500]: Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συνδυάζει διαφορετικές ασφαλιστικές ανάγκες και προσφέρει κλιμακωτές εκπτώσεις στα ασφάλιστρα

---
Title: None
Author: None
Datetime: 2026-02-06 10:54:00
Text[:500]: Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συνδυάζει διαφορετικές ασφαλιστικές ανάγκες και προσφέρει κλιμακωτές εκπτώσεις στα ασφάλιστρα

---
Title: None
Author: None
Datetime: 2026-05-19 10:04:54
Text[:500]: Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συνδυάζει διαφορετικές ασφαλιστικές ανάγκες και προσφέρει κλιμακωτές εκπτώσεις στα ασφάλιστρα

---
Title: None
Author: None
Datetime: 2026-05-06 09:35:47
Text[:500]: Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συνδυάζει διαφορετικές ασφαλιστικές ανάγκες και προσφέρει κλιμακωτές εκπτώσεις στα ασφάλιστρα

---
Title: None
Author: None
Datetime: 2026-03-26 12:32:46
Text[:500]: Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συνδυάζει διαφορετικές ασφαλιστικές ανάγκες και προσφέρει κλιμακωτές εκπτώσεις στα ασφάλιστρα

In [ ]:
extra_articles_list = []

for i, row in extra_teasers_df.iterrows():
    url = row["url"]
    print(f"{i+1}/{len(extra_teasers_df)}: {url}")

    try:
        response = requests.get(url, headers=HEADERS, timeout=15)
        doc = BeautifulSoup(response.text, "html.parser")

        # Use 'article' tag or the whole doc if not found, as in the protothema scraping logic
        article = doc.find("article") or doc

        full_article_dict = {}

        # website
        full_article_dict["site"] = "protothema.gr"

        # url
        full_article_dict["url"] = url

        # title
        title = article.find("h1").text.strip() if article.find("h1") else None
        full_article_dict["title"] = title

        # date from meta tag
        meta_date = doc.find("meta", {"property": "article:published_time"})
        date = meta_date["content"] if meta_date else None
        full_article_dict["date"] = date

        # author from JSON-LD
        author = None
        for script in doc.find_all("script", type="application/ld+json"):
            try:
                data = json.loads(script.string)
            except (TypeError, ValueError):
                continue
            if isinstance(data, dict) and "author" in data:
                a = data["author"]
                if isinstance(a, dict):
                    author = a.get("name")
                elif isinstance(a, list) and a:
                    author = a[0].get("name")
                break
        full_article_dict["author"] = author

        # full_text
        p_texts_list = []
        for p in article.find_all("p"):
            text = p.text.strip()
            if not text:
                continue
            if any(stop in text for stop in STOP_PHRASES):
                break
            p_texts_list.append(text)
        full_text = " ".join(p_texts_list)
        full_text = "".join(full_text.splitlines())
        full_article_dict["full_text"] = full_text if full_text else None

    except Exception as e:
        print("  -> Σφάλμα:", e)
        full_article_dict = {
            "site": "protothema.gr", "url": url, "title": None,
            "date": None, "author": None, "full_text": None,
        }

    extra_articles_list.append(full_article_dict)
    time.sleep(1)

protothema_extra_articles_df = pd.DataFrame(extra_articles_list)

# Convert date (string) to actual datetime
protothema_extra_articles_df["datetime"] = pd.to_datetime(protothema_extra_articles_df["date"], errors="coerce", utc=True)
protothema_extra_articles_df["datetime"] = protothema_extra_articles_df["datetime"].dt.tz_convert("Europe/Athens").dt.tz_localize(None)

protothema_extra_articles_df = protothema_extra_articles_df[["site", "url", "title", "date", "author", "full_text", "datetime"]]
protothema_extra_articles_df.head()

1/19: https://www.protothema.gr/technology/article/1880810/ereunites-kuvernoasfaleias-hakaran-tin-openai-me-ergaleio-tis-anthropic-nees-anisuhies-gia-tin-prostasia-ton-modelon-ai/
5/19: https://www.protothema.gr/technology/article/1880080/h-openai-apokalupse-nea-peristatika-me-tin-tehniti-noimosuni-oi-aprosdokites-i-anisuhitikes-suberifores-ton-modelon/
10/19: https://www.protothema.gr/technology/article/1879087/tehniti-noimosuni-horis-frena-oi-dimiourgoi-tis-ai-arhisan-na-fovoudai/
15/19: https://www.protothema.gr/technology/article/1878986/o-bil-geits-proeidopoiei-kamia-kuvernisi-ston-kosmo-den-einai-etoimi-gia-tis-allages-pou-tha-ferei-i-tehniti-noimosuni/
20/19: https://www.protothema.gr/technology/article/1878881/trab-kata-ton-periorismon-stin-ai-ta-robot-den-tha-katalavoun-ton-kosmo/
24/19: https://www.protothema.gr/technology/article/1878018/i-ai-diavazei-tin-kardia-prin-nosisei-ti-apokaluptoun-mastografia-kai-fotografies-prosopou/
27/19: https://www.protothema.gr/technology/article/1876521/to-iphone-duo-pou-diplonei-kai-kostizei-2399-euro-epanastatis-i-ouragos/
31/19: https://www.protothema.gr/technology/article/1876359/apo-1999-to-neo-anadiploumeno-iphone-duo-pou-kukloforei-stis-16-oktovriou-sta-1199-to-iphone-18/
35/19: https://www.protothema.gr/technology/article/1875474/mihail-kai-nemesis-oi-duo-ai-kathigites-tis-elas-pou-ekpaideuoun-polites-stin-psifiaki-asfaleia/
38/19: https://www.protothema.gr/technology/article/1875417/adistrofi-metrisi-gia-tin-parousiasi-tou-anadiploumenou-iphone-to-proto-megalo-stoihima-tou-neou-ceo-tis-apple/
42/19: https://www.protothema.gr/technology/article/1873826/i-openai-arhizei-ti-diathesi-tou-proigmenou-gpt-6-astra-uposhetai-austires-diklides-asfaleias/
45/19: https://www.protothema.gr/technology/article/1873792/h-lego-kanei-voutia-sti-nostalgia-me-to-eduposiako-proto-playstation-deite-video/
49/19: https://www.protothema.gr/technology/article/1873733/robot-sti-rosia-tsadistike-epeidi-to-esproxe-pelatis-kai-tou-epitethike-deite-video/
53/19: https://www.protothema.gr/technology/article/1873567/maziko-blak-aout-se-upiresies-ai-provlimata-se-chatgpt-claude-grok-gemini-kai-cursor/
57/19: https://www.protothema.gr/technology/article/1872806/o-tim-kouk-apohorei-apo-to-timoni-tis-apple-alla-paramenei-stin-etaireia-me-paketo-apodohon-47-ekat/
60/19: https://www.protothema.gr/technology/article/1871679/allagi-selidas-stin-apple-o-tim-kouk-paradidei-ta-inia-ston-tzon-ternous-i-proklisi-tis-ai-kai-to-stoihima-tis-kinas/
63/19: https://www.protothema.gr/technology/article/1871325/pos-i-sumfonia-tis-meta-borei-na-allaxei-to-diadiktuo-ti-provlepei-o-sumvivasmos-35-selidon-kai-i-stasi-tis-europis/
67/19: https://www.protothema.gr/technology/article/1870270/imerisio-orio-sigasi-eidopoiiseon-apokrupsi-ton-likes-oi-allages-pou-erhodai-se-facebook-instagram-meta-ti-diki/
71/19: https://www.protothema.gr/technology/article/1869736/o-bil-geits-mila-gia-tin-apeili-tis-tehnitis-noimosunis-stis-theseis-ergasias-kai-tin-anthropini-zoi/

,site,url,title,date,author,full_text,datetime
0,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-18T14:02:00+03:00,None,None,2026-09-18 14:02:00
1,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-17T09:50:00+03:00,None,None,2026-09-17 09:50:00
2,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-15T16:49:00+03:00,Δημήτρης Παγαδάκης,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-09-15 16:49:00
3,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-15T10:33:00+03:00,None,None,2026-09-15 10:33:00
4,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-09-15T07:05:00+03:00,None,None,2026-09-15 07:05:00

In [ ]:
protothema_2026_df.loc[0, 'full_text']

'Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συνδυάζει διαφορετικές ασφαλιστικές ανάγκες και προσφέρει κλιμακωτές εκπτώσεις στα ασφάλιστρα'

In [ ]:
protothema_2026_df.loc[0, 'date']

'2026-01-03T22:40:00+02:00'

In [ ]:
protothema_2026_df['clean_text'] = protothema_2026_df['full_text'].str.replace(
    "Ακολουθήστε το πρωτοθέμα στο Google News", "", regex=False
)

In [ ]:
protothema_2026_df['datetime'] = pd.to_datetime(
    protothema_2026_df['date'], format='%Y-%m-%dT%H:%M:%S%z'
)
protothema_2026_df.head()

/tmp/ipykernel_780/1484539430.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  protothema_2026_df['datetime'] = pd.to_datetime(

,site,url,title,date,author,full_text,datetime,clean_text
0,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-03T22:40:00+02:00,Κώστας Μαρτάκης,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-03 22:40:00+02:00,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...
1,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-05T17:58:00+02:00,None,None,2026-01-05 17:58:00+02:00,None
2,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-06T16:51:00+02:00,None,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-06 16:51:00+02:00,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...
3,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-09T15:14:08+02:00,None,None,2026-01-09 15:14:08+02:00,None
4,protothema.gr,https://www.protothema.gr/technology/article/1...,None,2026-01-10T08:30:02+02:00,None,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-10 08:30:02+02:00,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...

In [ ]:
protothema_2026_df = pd.read_csv('protothema_technology_2026.csv')
protothema_2026_df['datetime'] = pd.to_datetime(
    protothema_2026_df['date'], format='%Y-%m-%dT%H:%M:%S%z'
)

/tmp/ipykernel_780/2108615219.py:2: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  protothema_2026_df['datetime'] = pd.to_datetime(

In [ ]:
print(protothema_2026_df.shape)
protothema_2026_df

(92, 7)

,site,url,title,date,author,full_text,datetime
0,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-01-03T22:40:00+02:00,Κώστας Μαρτάκης,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-03 22:40:00+02:00
1,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-01-05T17:58:00+02:00,NaN,NaN,2026-01-05 17:58:00+02:00
2,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-01-06T16:51:00+02:00,NaN,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-06 16:51:00+02:00
3,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-01-09T15:14:08+02:00,NaN,NaN,2026-01-09 15:14:08+02:00
4,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-01-10T08:30:02+02:00,NaN,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-10 08:30:02+02:00
...,...,...,...,...,...,...,...
87,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-09-10T07:09:00+03:00,Βασίλης Τσακίρογλου,NaN,2026-09-10 07:09:00+03:00
88,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-09-10T10:46:00+03:00,NaN,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-09-10 10:46:00+03:00
89,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-09-13T10:48:00+03:00,NaN,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-09-13 10:48:00+03:00
90,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-09-15T16:49:00+03:00,Δημήτρης Παγαδάκης,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-09-15 16:49:00+03:00
91,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-09-17T09:50:00+03:00,NaN,NaN,2026-09-17 09:50:00+03:00

In [ ]:
protothema_2026_df.to_csv("protothema_technology_2026.csv", index=False, encoding="utf-8-sig")

In [ ]:
import base64
import requests
from google.colab import userdata

def save_df_to_github(df, repo, path, token=None, branch="main", message="Update dataset"):
    token = token or userdata.get("GITHUB_TOKEN")
    csv_content = df.to_csv(index=False, encoding="utf-8-sig")
    content_b64 = base64.b64encode(csv_content.encode("utf-8-sig")).decode("utf-8")

    url = f"https://api.github.com/repos/{repo}/contents/{path}"
    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}

    existing = requests.get(url, headers=headers, params={"ref": branch})
    sha = existing.json().get("sha") if existing.status_code == 200 else None

    payload = {"message": message, "content": content_b64, "branch": branch}
    if sha:
        payload["sha"] = sha

    response = requests.put(url, headers=headers, json=payload)
    response.raise_for_status()
    print(f"✅ Αποθηκεύτηκε: https://github.com/{repo}/blob/{branch}/{path}")
    return response.json()

save_df_to_github(
    protothema_2026_df,
    repo="annatsamoyra-prog/data-story-",
    path="protothema_technology_2026.csv",
    token=userdata.get("newtoken")
)

✅ Αποθηκεύτηκε: https://github.com/annatsamoyra-prog/data-story-/blob/main/protothema_technology_2026.csv

{'content': {'name': 'protothema_technology_2026.csv',
  'path': 'protothema_technology_2026.csv',
  'sha': 'b2f238ad9826c986955760c9a6a87bb5c728574a',
  'size': 35431,
  'url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/contents/protothema_technology_2026.csv?ref=main',
  'html_url': 'https://github.com/annatsamoyra-prog/data-story-/blob/main/protothema_technology_2026.csv',
  'git_url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/blobs/b2f238ad9826c986955760c9a6a87bb5c728574a',
  'download_url': 'https://raw.githubusercontent.com/annatsamoyra-prog/data-story-/main/protothema_technology_2026.csv',
  'type': 'file',
  '_links': {'self': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/contents/protothema_technology_2026.csv?ref=main',
   'git': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/blobs/b2f238ad9826c986955760c9a6a87bb5c728574a',
   'html': 'https://github.com/annatsamoyra-prog/data-story-/blob/main/protothema_technology_2026.csv'}},
 'commit': {'sha': '424026204e1473824a704f8c07755964af56594d',
  'node_id': 'C_kwDOUZNHjNoAKDQyNDAyNjIwNGUxNDczODI0YTcwNGY4YzA3NzU1OTY0YWY1NjU5NGQ',
  'url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/commits/424026204e1473824a704f8c07755964af56594d',
  'html_url': 'https://github.com/annatsamoyra-prog/data-story-/commit/424026204e1473824a704f8c07755964af56594d',
  'author': {'name': 'annatsamoyra-prog',
   'email': 'anna.tsamoyra@gmail.com',
   'date': '2026-09-19T10:37:44Z'},
  'committer': {'name': 'annatsamoyra-prog',
   'email': 'anna.tsamoyra@gmail.com',
   'date': '2026-09-19T10:37:44Z'},
  'tree': {'sha': '4c22b295350676518ad6dd6263f5b21b37729ad5',
   'url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/trees/4c22b295350676518ad6dd6263f5b21b37729ad5'},
  'message': 'Update dataset',
  'parents': [{'sha': '247c63eee405ed30e52788c85ae9b24b57c52508',
    'url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/commits/247c63eee405ed30e52788c85ae9b24b57c52508',
    'html_url': 'https://github.com/annatsamoyra-prog/data-story-/commit/247c63eee405ed30e52788c85ae9b24b57c52508'}],
  'verification': {'verified': False,
   'reason': 'unsigned',
   'signature': None,
   'payload': None,
   'verified_at': None}}}

In [38]:
nan_rows = protothema_2026_df[protothema_2026_df['full_text'].isna()]
nan_rows

Empty DataFrame
Columns: [site, url, title, date, author, full_text, datetime]
Index: []

In [36]:
nan_rows = protothema_2026_df[protothema_2026_df['full_text'].isna()]
protothema_2026_df = protothema_2026_df.drop(nan_rows.index)
protothema_2026_df.to_csv("protothema_technology_2026.csv", index=False, encoding="utf-8-sig")

In [39]:
duplicates = protothema_2026_df.duplicated(subset=['full_text']).any()
duplicates

np.True_

In [42]:
protothema_2026_df = protothema_2026_df.drop_duplicates(subset='full_text', keep='first').reset_index(drop=True)

In [44]:
# βεβαιώνομαι οτι η ημερομηνία μου έχει format datetime
protothema_2026_df['date'] = pd.to_datetime(protothema_2026_df['date'], errors='coerce')

In [46]:
protothema_2026_df['text'] = protothema_2026_df['full_text'].fillna('')

In [47]:

#εισάγω τη βιβιοθήκη re για δημιουργία regex (regular expressions)-δηλαδή κανόνες αναζήτησης και εντοπισμού μοτίβων
import re

In [48]:
# δημιουργώ regex patterns που εντοπίζουν προβληματικά μοτίβα για βασικό καθαρισμό κειμένου (δηλ. τι ψάχνω)

url      = re.compile(r'https?://\S+|www\.\S+')  # εντοπίζει URLs/links
mentions  = re.compile(r'@\w+')                  # εντοπίζει mentions π.χ. @username
dashes   = re.compile(r'[-–—−]+')                # εντοπίζει όλα τα είδη παύλας (– — − κτλ.) και τα κανονικοποιεί
quotes   = re.compile(r'[“”]')                   # εντοπίζει “curly” διπλά εισαγωγικά
apos     = re.compile(r'[’]')                    # εντοπιζει το curly απόστροφο (’)
spaces   = re.compile(r'\s+')                    # εντοπίζει πολλά συνεχόμενα κενά

In [50]:
# φτιάχνω συνάρτηση που εφαρμόζει τα παραπάνω μοτίβα και κάνει την πραγματική κανονικοποίηση του κειμένου (δηλ. τι κάνω όταν εντοπίσω το πρόβλημα)
# ηπιος καθαρισμός, δεν αφαιρούμε τη στίξη

def mild_text_clean(text: str) -> str:

    text = str(text)

    text = url.sub(" ", text)        # αφαιρεί links
    text = mentions.sub(" ", text)    # αφαιρεί mentions
    text = dashes.sub(" — ", text)   # ενοποιεί τις παύλες σε em dash
    text = quotes.sub('"', text)     # κάνει “ ” → "
    text = apos.sub("'", text)       # κάνει ’ → '
    text = spaces.sub(" ", text).strip()  # αφαιρεί περιττά κενά

    return text

In [51]:
#εφαρμοζω τη συναρτηση και αποθηκεύω σε νέα στήλη

protothema_2026_df["text_clean"] = protothema_2026_df["text"].apply(mild_text_clean)

In [52]:
# check
protothema_2026_df.head()

,site,url,title,date,author,full_text,datetime,text,text_clean
0,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-01-03 22:40:00+02:00,Κώστας Μαρτάκης,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-03 22:40:00+02:00,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...

In [55]:
import string

def clean_text(article: str) -> str:
    s = str(article).lower() # mετατρέπει το κείμενο σε string και όλα τα γράμματα σε πεζά
    s = re.sub(r'[' + re.escape(string.punctuation) + r'’“”–—]', ' ', s) # αντικαθιστά όλα τα σημεία στίξης με κενό
    s = re.sub(r'\s+', ' ', s).strip() # αφαιρεί τα περιττά κενά ανάμεσα στις λέξεις

    return s

In [56]:
protothema_2026_df['tokenized'] = protothema_2026_df['text_clean'].map(lambda x: clean_text(x))

In [57]:
protothema_2026_df.tail

<bound method NDFrame.tail of             site                                                url  title  \
0  protothema.gr  https://www.protothema.gr/technology/article/1...    NaN

                       date           author  \
0 2026-01-03 22:40:00+02:00  Κώστας Μαρτάκης

                                           full_text  \
0  Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...

                    datetime  \
0  2026-01-03 22:40:00+02:00

                                                text  \
0  Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...

                                          text_clean  \
0  Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...

                                           tokenized
0  το πρόγραμμα eurolifesyn της eurolife ffh συνδ...  >

In [59]:
import string

import nltk

# Αφαίρεση Stopwords

# εισάγω βιβλιοθήκες και εργαλεία για tokenization και stopwords

# η βιβλιοθήκη string περιέχει έτοιμους χαρακτήρες και εργαλεία για επεξεργασία κειμένου


#η nltk (Natural Language Toolkit) χρησιμοποιείται για βασικές εργασίες NLP (Natural Language Processing) όπως tokenization, stopwords κτλ.


# κατεβάζω το tokenizer μοντέλο punkt που χρησιμοποιείται για sentence splitting και tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

# παίρνω όλα τα σημεία στίξης και τα αποθηκεύω σε λίστα
punct = list(set(string.punctuation))

## εισάγω τα stopwords της NLTK
from nltk.corpus import stopwords

#εισάγω tokenizer για να χωρίσω το κείμενο σε λέξεις/tokens
from nltk.tokenize import word_tokenize

# κατεβάζω τη λίστα stopwords
nltk.download('stopwords')

## δημιουργώ set με τα αγγλικά stopwords
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [60]:

def remove_stopwords(x):

    # ελέγχω αν το input είναι ήδη λίστα από tokens ή κανονικό κείμενο/string
    tokens = x if isinstance(x, (list, tuple)) else word_tokenize(str(x))

    # κρατάω μόνο τις λέξεις που ΔΕΝ είναι stopwords
    return [t for t in tokens if t.lower() not in stop_words]

In [61]:
#εφαρμοζω τη συναρτηση και αποθηκεύω σε νέα στήλη

protothema_2026_df['no_stop'] = protothema_2026_df['tokenized'].apply(remove_stopwords)

In [62]:
protothema_2026_df.head(2)

,site,url,title,date,author,full_text,datetime,text,text_clean,tokenized,no_stop
0,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-01-03 22:40:00+02:00,Κώστας Μαρτάκης,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-03 22:40:00+02:00,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,το πρόγραμμα eurolifesyn της eurolife ffh συνδ...,"[το, πρόγραμμα, eurolifesyn, της, eurolife, ff..."

In [63]:
protothema_2026_df['num_wds'] = protothema_2026_df['tokenized'].apply(lambda x: len(x.split()))#αποθηκεύω τον αριθμό λέξεων του άρθρου σε δική του στήλη
protothema_2026_df['num_wds'].mean()

np.float64(16.0)

In [64]:
# συχνότητα μοναδικών λέξεων ανα κείμενο
protothema_2026_df['uniq_wds'] = protothema_2026_df['tokenized'].str.split().apply(lambda x: len(set(x))) #αποθηκεύω τον αριθμό μοναδικών λεξεων του άρθρου σε δική του στήλη
protothema_2026_df['uniq_wds'].mean()

np.float64(16.0)

In [65]:
# δημιουργώ στήλη Text_id για να μην χάνω τα κείμενα
protothema_2026_df = protothema_2026_df.reset_index().rename(columns={'index': 'Text_id'})

In [66]:
protothema_2026_df.head()

,Text_id,site,url,title,date,author,full_text,datetime,text,text_clean,tokenized,no_stop,num_wds,uniq_wds
0,0,protothema.gr,https://www.protothema.gr/technology/article/1...,NaN,2026-01-03 22:40:00+02:00,Κώστας Μαρτάκης,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,2026-01-03 22:40:00+02:00,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,Το πρόγραμμα EurolifeSYN+ της Eurolife FFH συν...,το πρόγραμμα eurolifesyn της eurolife ffh συνδ...,"[το, πρόγραμμα, eurolifesyn, της, eurolife, ff...",16,16

In [67]:
protothema_2026_df.to_csv('https://github.com/annatsamoyra-prog/data-story-.git')

In [70]:
save_df_to_github(
    protothema_2026_df,
    repo="annatsamoyra-prog/data-story-",
    path="protothema_technology_2026_csv_clean.csv",
    token=userdata.get("newtoken")
)

✅ Αποθηκεύτηκε: https://github.com/annatsamoyra-prog/data-story-/blob/main/protothema_technology_2026_csv_clean.csv

{'content': {'name': 'protothema_technology_2026_csv_clean.csv',
  'path': 'protothema_technology_2026_csv_clean.csv',
  'sha': '66bb4833d30d899a7f7ff574e54f52d3e1fda13a',
  'size': 1591,
  'url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/contents/protothema_technology_2026_csv_clean.csv?ref=main',
  'html_url': 'https://github.com/annatsamoyra-prog/data-story-/blob/main/protothema_technology_2026_csv_clean.csv',
  'git_url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/blobs/66bb4833d30d899a7f7ff574e54f52d3e1fda13a',
  'download_url': 'https://raw.githubusercontent.com/annatsamoyra-prog/data-story-/main/protothema_technology_2026_csv_clean.csv',
  'type': 'file',
  '_links': {'self': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/contents/protothema_technology_2026_csv_clean.csv?ref=main',
   'git': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/blobs/66bb4833d30d899a7f7ff574e54f52d3e1fda13a',
   'html': 'https://github.com/annatsamoyra-prog/data-story-/blob/main/protothema_technology_2026_csv_clean.csv'}},
 'commit': {'sha': '16763eef4f45cc7b4b06a0a366801868913c3a3d',
  'node_id': 'C_kwDOUZNHjNoAKDE2NzYzZWVmNGY0NWNjN2I0YjA2YTBhMzY2ODAxODY4OTEzYzNhM2Q',
  'url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/commits/16763eef4f45cc7b4b06a0a366801868913c3a3d',
  'html_url': 'https://github.com/annatsamoyra-prog/data-story-/commit/16763eef4f45cc7b4b06a0a366801868913c3a3d',
  'author': {'name': 'annatsamoyra-prog',
   'email': 'anna.tsamoyra@gmail.com',
   'date': '2026-09-19T11:00:40Z'},
  'committer': {'name': 'annatsamoyra-prog',
   'email': 'anna.tsamoyra@gmail.com',
   'date': '2026-09-19T11:00:40Z'},
  'tree': {'sha': '86d73b9f62787c5f56366efbbe02d90f303a19b5',
   'url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/trees/86d73b9f62787c5f56366efbbe02d90f303a19b5'},
  'message': 'Update dataset',
  'parents': [{'sha': '56ee25292f386fc52ed7c92d3f5d780d7fbab259',
    'url': 'https://api.github.com/repos/annatsamoyra-prog/data-story-/git/commits/56ee25292f386fc52ed7c92d3f5d780d7fbab259',
    'html_url': 'https://github.com/annatsamoyra-prog/data-story-/commit/56ee25292f386fc52ed7c92d3f5d780d7fbab259'}],
  'verification': {'verified': False,
   'reason': 'unsigned',
   'signature': None,
   'payload': None,
   'verified_at': None}}}